version: '3.7'
services:
  minio:
    image: minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin           # Administrator foydalanuvchi nomi
      MINIO_ROOT_PASSWORD: admin123    # Administrator paroli
    volumes:
      - minio-data:/data               # Saqlash uchun hajm
    command: server /data --console-address ":9001"

volumes:
  minio-data:
    driver: local